// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5dYnbh73kVOfghSMzaMjgb2I-SG6C_yY',
    appId: '1:167217905484:web:3188531c3d9c4e264419e9',
    messagingSenderId: '167217905484',
    projectId: 'chat-app-74583',
    authDomain: 'chat-app-74583.firebaseapp.com',
    storageBucket: 'chat-app-74583.appspot.com',
    measurementId: 'G-9ZCXTSETXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4EsvGt73Ecc5yEpKHYxSPLOwUzzlJjeA',
    appId: '1:167217905484:android:ada0e80a1f5738ed4419e9',
    messagingSenderId: '167217905484',
    projectId: 'chat-app-74583',
    storageBucket: 'chat-app-74583.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiDnjG59ofm3XUgdf9r0BS5vfdRstRaJk',
    appId: '1:167217905484:ios:479770a814f194a64419e9',
    messagingSenderId: '167217905484',
    projectId: 'chat-app-74583',
    storageBucket: 'chat-app-74583.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiDnjG59ofm3XUgdf9r0BS5vfdRstRaJk',
    appId: '1:167217905484:ios:479770a814f194a64419e9',
    messagingSenderId: '167217905484',
    projectId: 'chat-app-74583',
    storageBucket: 'chat-app-74583.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5dYnbh73kVOfghSMzaMjgb2I-SG6C_yY',
    appId: '1:167217905484:web:66841bf33d868d714419e9',
    messagingSenderId: '167217905484',
    projectId: 'chat-app-74583',
    authDomain: 'chat-app-74583.firebaseapp.com',
    storageBucket: 'chat-app-74583.appspot.com',
    measurementId: 'G-BJ76WV5ZW9',
  );
}
